### ISSUE TITLE
Doctest failures on GHC 8.10

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/lens#874]
For some reasons, the `doctests` test suite is failing on GHC 8.8 in particular. [Here](https://travis-ci.org/ekmett/lens/jobs/549463804#L1903) is an excerpt from a recent build:

```
Test suite doctests: RUNNING... 
/tmp/dist-test.2aHF/lens-4.18/src/Data/Data/Lens.hs:161: failure in expression `(2,4) & upon fst *~ 5'
expected: (10,4)
 but got: 
          <interactive>:1241:9: error:
              Variable not in scope:
                upon
                  :: ((a0, b0) -> a0) -> ASetter (Integer, Integer) b Integer Integer

/tmp/dist-test.2aHF/lens-4.18/src/Data/Data/Lens.hs:210: failure in expression `upon' (tail.tail) .~ [10,20] $ [1,2,3,4]'
expected: [1,2,10,20]
 but got: 
          <interactive>:1249:1: error:
              Variable not in scope:
                upon' :: ([a0] -> [a0]) -> ASetter [Integer] t a1 [Integer]

/tmp/dist-test.2aHF/lens-4.18/src/Data/Data/Lens.hs:232: failure in expression `onceUpon (tail.tail) .~ [10,20] $ [1,2,3,4] -- BAD'
expected: [1,10,20]
 but got: 
          <interactive>:1257:1: error:
              Variable not in scope:
                onceUpon :: ([a0] -> [a0]) -> ASetter [Integer] t a1 [Integer]

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Traversal.hs:757: failure in expression `('a' :| "bc") ^. head1'
expected: 'a'
 but got: 
          <interactive>:2371:6: error:
              • Data constructor not in scope: (:|) :: Char -> [Char] -> f10 b
              • Perhaps you meant one of these:
                  ‘NonEmpty.:|’ (imported from Data.List.NonEmpty),
                  ‘:>’ (imported from Control.Lens),
                  ‘:<’ (imported from Control.Lens)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:530: failure in expression `foldMapOf (folded . both . _Just) Sum [(Just 21, Just 21)]'
expected: Sum {getSum = 42}
 but got: 
          <interactive>:3105:35: error:
              • Data constructor not in scope: Sum :: Integer -> r
              • Perhaps you meant variable ‘sum’ (imported from Prelude)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:563: failure in expression `foldOf (folded.folded) [[Sum 1,Sum 4],[Sum 8, Sum 8],[Sum 21]]'
expected: Sum {getSum = 42}
 but got: 
          <interactive>:3139:26: error:
              • Data constructor not in scope: Sum :: Integer -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:3139:32: error:
              • Data constructor not in scope: Sum :: Integer -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:3139:40: error:
              • Data constructor not in scope: Sum :: Integer -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:3139:47: error:
              • Data constructor not in scope: Sum :: Integer -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:3139:55: error:
              • Data constructor not in scope: Sum :: Integer -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:1346: failure in expression `first1Of traverse1 (1 :| [2..10])'
expected: 1
 but got: 
          <interactive>:4141:23: error:
              • Data constructor not in scope:
                  (:|) :: Integer -> [Integer] -> t0 a
              • Perhaps you meant one of these:
                  ‘NonEmpty.:|’ (imported from Data.List.NonEmpty),
                  ‘:>’ (imported from Control.Lens),
                  ‘:<’ (imported from Control.Lens)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:1400: failure in expression `last1Of traverse1 (1 :| [2..10])'
expected: 10
 but got: 
          <interactive>:4213:22: error:
              • Data constructor not in scope:
                  (:|) :: Integer -> [Integer] -> t0 a
              • Perhaps you meant one of these:
                  ‘NonEmpty.:|’ (imported from Data.List.NonEmpty),
                  ‘:>’ (imported from Control.Lens),
                  ‘:<’ (imported from Control.Lens)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:1527: failure in expression `maximum1Of traverse1 (1 :| [2..10])'
expected: 10
 but got: 
          <interactive>:4365:25: error:
              • Data constructor not in scope:
                  (:|) :: Integer -> [Integer] -> t0 a
              • Perhaps you meant one of these:
                  ‘NonEmpty.:|’ (imported from Data.List.NonEmpty),
                  ‘:>’ (imported from Control.Lens),
                  ‘:<’ (imported from Control.Lens)
/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:1577: failure in expression `minimum1Of traverse1 (1 :| [2..10])'
expected: 1
 but got: 
          <interactive>:4437:25: error:
              • Data constructor not in scope:
                  (:|) :: Integer -> [Integer] -> t0 a
              • Perhaps you meant one of these:
                  ‘NonEmpty.:|’ (imported from Data.List.NonEmpty),
                  ‘:>’ (imported from Control.Lens),
                  ‘:<’ (imported from Control.Lens)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Lens.hs:878: failure in expression `(Sum a,b) & _1 <<<>~ Sum c'
expected: (Sum {getSum = a},(Sum {getSum = a + c},b))
 but got: 
          <interactive>:6089:2: error:
              • Data constructor not in scope: Sum :: Expr -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:6089:22: error:
              • Data constructor not in scope: Sum :: Expr -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Lens.hs:1259: failure in expression `overA _1 ((+1) *** (+2)) ((1,2),6)'
expected: ((2,4),6)
 but got: 
          <interactive>:6119:16: error:
              • Variable not in scope:
                  (***)
                    :: (Integer -> Integer)
                       -> (Integer -> Integer) -> (Integer, Integer) -> b
              • Perhaps you meant one of these:
                  ‘**’ (imported from Prelude), ‘**~’ (imported from Control.Lens),
                  ‘**=’ (imported from Control.Lens)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Setter.hs:227: failure in expression `getPredicate (over contramapped (*2) (Predicate even)) 5'
expected: True
 but got: 
          <interactive>:6577:1: error:
              Variable not in scope: getPredicate :: f0 Integer -> Integer -> t
          
          <interactive>:6577:39: error:
              Data constructor not in scope:
                Predicate :: (Integer -> Bool) -> f0 Integer

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Setter.hs:1048: failure in expression `(Sum a,b) & _1 <>~ Sum c'
expected: (Sum {getSum = a + c},b)
 but got: 
          <interactive>:7501:2: error:
              • Data constructor not in scope: Sum :: Expr -> b
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:7501:20: error:
              • Data constructor not in scope: Sum :: Expr -> b
              • Perhaps you meant variable ‘sum’ (imported from Prelude)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Setter.hs:1069: failure in expression `execState (do _1 <>= Sum c; _2 <>= Product d) (Sum a,Product b)'
expected: (Sum {getSum = a + c},Product {getProduct = b * d})
 but got: 
          <interactive>:7529:22: error:
              • Data constructor not in scope: Sum :: Expr -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:7529:36: error:
              • Data constructor not in scope: Product :: Expr -> b
              • Perhaps you meant variable ‘product’ (imported from Prelude)
          
          <interactive>:7529:48: error:
              • Data constructor not in scope: Sum :: Expr -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:7529:54: error:
              • Data constructor not in scope: Product :: Expr -> b
              • Perhaps you meant variable ‘product’ (imported from Prelude)

Examples: 895  Tried: 878  Errors: 0  Failures: 15
```

I haven't figured out what is going wrong yet.

**Comment by phadej** [comment]
Looks like the module isn't loaded when `doctest` tries to run tests

**Comment by RyanGlScott** [comment]
After lots of digging, I've reduced this down to a fairly minimal example. You'll need two `.hs` files:

```hs
module Internal () where
```
```hs
{-# LANGUAGE UnboxedTuples #-}                                                                     
module Label where                                                                                 
                                                                                                   
-- |                                                                                               
-- >>> foo                                                                                         
-- 42                                                                                              
foo :: Int                                                                                         
foo = 42
```

If I use a version of `doctest` built with GHC 8.6.5, then this works:

```
$ doctest Internal Label
Examples: 1  Tried: 1  Errors: 0  Failures: 0
```

However, if I use a version of `doctest` build with GHC 8.8.1, then it fails:

```
$ doctest Internal Label
Label.hs:5: failure in expression `foo'      
expected: 42
 but got: 
          <interactive>:23:1: error: Variable not in scope: foo

Examples: 1  Tried: 1  Errors: 0  Failures: 1
```

Some observations:

* It is crucial that the arguments to `doctest` are passed in the order `Internal Label`. The error does not occur if you pass just `Internal`, just `Label`, or `Label Internal`.
* Enabling `UnboxedTuples` is also crucial, since the error does not occur without it.
* This issue bears a striking similarity to sol/doctest#160. (In fact, remembering that issue is what helped me minimize this.) Unlike sol/doctest#160, however, you do not need to pass `-fobject-code` in order to trigger the issue.

I'm still not sure if this is a regression in `doctest`, GHC 8.8, or a combination thereof.

**Comment by RyanGlScott** [comment]
I'm inclined to blame this on GHC 8.8 itself. When `doctest` is invoked on some files, loads them into GHCi, invokes `:m *<Mod>` on any module `Mod` with doctests, and then runs those doctests. Here is what happens if you do this on GHCi 8.6.5:

```
$ /opt/ghc/8.6.5/bin/ghci Internal.hs Label.hs
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
[1 of 2] Compiling Internal         ( Internal.hs, interpreted )
[2 of 2] Compiling Label            ( Label.hs, interpreted )
Ok, two modules loaded.
λ> :m *Label
λ> foo
42
```

However, if you do the same with GHC 8.8.1:

```
$ /opt/ghc/8.8.1/bin/ghci Internal.hs Label.hs
GHCi, version 8.8.0.20190613: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
[1 of 2] Compiling Internal         ( Internal.hs, interpreted )
[2 of 2] Compiling Label            ( Label.hs, /tmp/ghc9732_0/ghc_2.o )
Ok, two modules loaded.
λ> :m *Label
module 'Label' is not interpreted; try ':add *Label' first
λ> foo

<interactive>:2:1: error: Variable not in scope: foo
```

I've filed an issue upstream at https://gitlab.haskell.org/ghc/ghc/issues/16876.

**Comment by RyanGlScott** [comment]
An update: the offending commit was reverted from the `ghc-8.8` branch to give libraries more time to adapt to this change, so this no longer affects GHC 8.8. The commit is still present on GHC HEAD, however, so there is a remaining question of how to resolve the tension between it and `lens`' doctests.

I currently have a GHC merge request in the works (https://gitlab.haskell.org/ghc/ghc/merge_requests/1553) that will make it so that enabling the `-fbyte-code` flag will cancel the automatic use of object code when `UnboxedTuples` is enabled. This will allow us to avoid `lens`' doctests from breaking, although we will have to patch `lens` to add `{-# OPTIONS_GHC -fbyte-code #-}` in one place. Thankfully, this is backwards-compatible with older GHCs, so this is a low price to pay.

**Comment by RyanGlScott** [comment]
Well, I _thought_ `{-# OPTIONS_GHC -fbyte-code #-}` would be backwards-compatible with old GHCs. In practice, it turns out that adding this option to `Data.Data.Lens` unconditionally causes problems for Haddock [on GHC 7.8.4](https://travis-ci.org/ekmett/lens/jobs/641808908#L1950) and [on GHC 7.4.2](https://travis-ci.org/ekmett/lens/jobs/641808910#L2076) (and literally no other GHC versions). In light of this, I think I'll just guard `{-# OPTIONS_GHC -fbyte-code #-}` behind `#if __GLASGOW_HASKELL__ >= 810 ... #endif`.

**Comment by RyanGlScott** [comment]
See #912.
