### PR TITLE
Support GHC 8.10

### LINKED ISSUE #874: Doctest failures on GHC 8.10
For some reasons, the `doctests` test suite is failing on GHC 8.8 in particular. [Here](https://travis-ci.org/ekmett/lens/jobs/549463804#L1903) is an excerpt from a recent build:

```
Test suite doctests: RUNNING... 
/tmp/dist-test.2aHF/lens-4.18/src/Data/Data/Lens.hs:161: failure in expression `(2,4) & upon fst *~ 5'
expected: (10,4)
 but got: 
          <interactive>:1241:9: error:
              Variable not in scope:
                upon
                  :: ((a0, b0) -> a0) -> ASetter (Integer, Integer) b Integer Integer

/tmp/dist-test.2aHF/lens-4.18/src/Data/Data/Lens.hs:210: failure in expression `upon' (tail.tail) .~ [10,20] $ [1,2,3,4]'
expected: [1,2,10,20]
 but got: 
          <interactive>:1249:1: error:
              Variable not in scope:
                upon' :: ([a0] -> [a0]) -> ASetter [Integer] t a1 [Integer]

/tmp/dist-test.2aHF/lens-4.18/src/Data/Data/Lens.hs:232: failure in expression `onceUpon (tail.tail) .~ [10,20] $ [1,2,3,4] -- BAD'
expected: [1,10,20]
 but got: 
          <interactive>:1257:1: error:
              Variable not in scope:
                onceUpon :: ([a0] -> [a0]) -> ASetter [Integer] t a1 [Integer]

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Traversal.hs:757: failure in expression `('a' :| "bc") ^. head1'
expected: 'a'
 but got: 
          <interactive>:2371:6: error:
              • Data constructor not in scope: (:|) :: Char -> [Char] -> f10 b
              • Perhaps you meant one of these:
                  ‘NonEmpty.:|’ (imported from Data.List.NonEmpty),
                  ‘:>’ (imported from Control.Lens),
                  ‘:<’ (imported from Control.Lens)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:530: failure in expression `foldMapOf (folded . both . _Just) Sum [(Just 21, Just 21)]'
expected: Sum {getSum = 42}
 but got: 
          <interactive>:3105:35: error:
              • Data constructor not in scope: Sum :: Integer -> r
              • Perhaps you meant variable ‘sum’ (imported from Prelude)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:563: failure in expression `foldOf (folded.folded) [[Sum 1,Sum 4],[Sum 8, Sum 8],[Sum 21]]'
expected: Sum {getSum = 42}
 but got: 
          <interactive>:3139:26: error:
              • Data constructor not in scope: Sum :: Integer -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:3139:32: error:
              • Data constructor not in scope: Sum :: Integer -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:3139:40: error:
              • Data constructor not in scope: Sum :: Integer -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:3139:47: error:
              • Data constructor not in scope: Sum :: Integer -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:3139:55: error:
              • Data constructor not in scope: Sum :: Integer -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:1346: failure in expression `first1Of traverse1 (1 :| [2..10])'
expected: 1
 but got: 
          <interactive>:4141:23: error:
              • Data constructor not in scope:
                  (:|) :: Integer -> [Integer] -> t0 a
              • Perhaps you meant one of these:
                  ‘NonEmpty.:|’ (imported from Data.List.NonEmpty),
                  ‘:>’ (imported from Control.Lens),
                  ‘:<’ (imported from Control.Lens)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:1400: failure in expression `last1Of traverse1 (1 :| [2..10])'
expected: 10
 but got: 
          <interactive>:4213:22: error:
              • Data constructor not in scope:
                  (:|) :: Integer -> [Integer] -> t0 a
              • Perhaps you meant one of these:
                  ‘NonEmpty.:|’ (imported from Data.List.NonEmpty),
                  ‘:>’ (imported from Control.Lens),
                  ‘:<’ (imported from Control.Lens)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:1527: failure in expression `maximum1Of traverse1 (1 :| [2..10])'
expected: 10
 but got: 
          <interactive>:4365:25: error:
              • Data constructor not in scope:
                  (:|) :: Integer -> [Integer] -> t0 a
              • Perhaps you meant one of these:
                  ‘NonEmpty.:|’ (imported from Data.List.NonEmpty),
                  ‘:>’ (imported from Control.Lens),
                  ‘:<’ (imported from Control.Lens)
/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Fold.hs:1577: failure in expression `minimum1Of traverse1 (1 :| [2..10])'
expected: 1
 but got: 
          <interactive>:4437:25: error:
              • Data constructor not in scope:
                  (:|) :: Integer -> [Integer] -> t0 a
              • Perhaps you meant one of these:
                  ‘NonEmpty.:|’ (imported from Data.List.NonEmpty),
                  ‘:>’ (imported from Control.Lens),
                  ‘:<’ (imported from Control.Lens)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Lens.hs:878: failure in expression `(Sum a,b) & _1 <<<>~ Sum c'
expected: (Sum {getSum = a},(Sum {getSum = a + c},b))
 but got: 
          <interactive>:6089:2: error:
              • Data constructor not in scope: Sum :: Expr -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:6089:22: error:
              • Data constructor not in scope: Sum :: Expr -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Lens.hs:1259: failure in expression `overA _1 ((+1) *** (+2)) ((1,2),6)'
expected: ((2,4),6)
 but got: 
          <interactive>:6119:16: error:
              • Variable not in scope:
                  (***)
                    :: (Integer -> Integer)
                       -> (Integer -> Integer) -> (Integer, Integer) -> b
              • Perhaps you meant one of these:
                  ‘**’ (imported from Prelude), ‘**~’ (imported from Control.Lens),
                  ‘**=’ (imported from Control.Lens)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Setter.hs:227: failure in expression `getPredicate (over contramapped (*2) (Predicate even)) 5'
expected: True
 but got: 
          <interactive>:6577:1: error:
              Variable not in scope: getPredicate :: f0 Integer -> Integer -> t
          
          <interactive>:6577:39: error:
              Data constructor not in scope:
                Predicate :: (Integer -> Bool) -> f0 Integer

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Setter.hs:1048: failure in expression `(Sum a,b) & _1 <>~ Sum c'
expected: (Sum {getSum = a + c},b)
 but got: 
          <interactive>:7501:2: error:
              • Data constructor not in scope: Sum :: Expr -> b
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:7501:20: error:
              • Data constructor not in scope: Sum :: Expr -> b
              • Perhaps you meant variable ‘sum’ (imported from Prelude)

/tmp/dist-test.2aHF/lens-4.18/src/Control/Lens/Setter.hs:1069: failure in expression `execState (do _1 <>= Sum c; _2 <>= Product d) (Sum a,Product b)'
expected: (Sum {getSum = a + c},Product {getProduct = b * d})
 but got: 
          <interactive>:7529:22: error:
              • Data constructor not in scope: Sum :: Expr -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:7529:36: error:
              • Data constructor not in scope: Product :: Expr -> b
              • Perhaps you meant variable ‘product’ (imported from Prelude)
          
          <interactive>:7529:48: error:
              • Data constructor not in scope: Sum :: Expr -> a
              • Perhaps you meant variable ‘sum’ (imported from Prelude)
          
          <interactive>:7529:54: error:
              • Data constructor not in scope: Product :: Expr -> b
              • Perhaps you meant variable ‘product’ (imported from Prelude)

Examples: 895  Tried: 878  Errors: 0  Failures: 15
```

I haven't figured out what is going wrong yet.

### LINKED ISSUE #894: Lens doesn't build with GHC-8.10
Trying to build `lens` with the alpha version of `ghc` breaks.

I'm assuming that the Template Haskell API has a breaking change.

See the log (build with `cabal-3.0.0`):

```
Failed to build lens-4.18.1.
Build log (
/home/user/.cabal/logs/ghc-8.10.0.20191122/lens-4.18.1-e2a7d35ed33b9a8e8fda2522013213a57568ad425c088de17b1f4f50f795277d.log
):
[1 of 1] Compiling Main             ( /home/user/project-name/dist-newstyle/tmp/src-4827/lens-4.18.1/dist/setup/setup.hs, /home/user/project-name/dist-newstyle/tmp/src-4827/lens-4.18.1/dist/setup/Main.o )
Linking /home/user/project-name/dist-newstyle/tmp/src-4827/lens-4.18.1/dist/setup/setup ...
Configuring lens-4.18.1...
Preprocessing library for lens-4.18.1..
Building library for lens-4.18.1..
[ 1 of 84] Compiling Control.Lens.Internal.CTypes ( src/Control/Lens/Internal/CTypes.hs, dist/build/Control/Lens/Internal/CTypes.o, dist/build/Control/Lens/Internal/CTypes.dyn_o )
[ 2 of 84] Compiling Control.Lens.Internal.Coerce ( src/Control/Lens/Internal/Coerce.hs, dist/build/Control/Lens/Internal/Coerce.o, dist/build/Control/Lens/Internal/Coerce.dyn_o )
[ 3 of 84] Compiling Control.Lens.Internal.Getter ( src/Control/Lens/Internal/Getter.hs, dist/build/Control/Lens/Internal/Getter.o, dist/build/Control/Lens/Internal/Getter.dyn_o )
[ 4 of 84] Compiling Control.Lens.Internal.Fold ( src/Control/Lens/Internal/Fold.hs, dist/build/Control/Lens/Internal/Fold.o, dist/build/Control/Lens/Internal/Fold.dyn_o )
[ 5 of 84] Compiling Control.Lens.Internal.Instances ( src/Control/Lens/Internal/Instances.hs, dist/build/Control/Lens/Internal/Instances.o, dist/build/Control/Lens/Internal/Instances.dyn_o )
[ 6 of 84] Compiling Control.Lens.Internal.Indexed ( src/Control/Lens/Internal/Indexed.hs, dist/build/Control/Lens/Internal/Indexed.o, dist/build/Control/Lens/Internal/Indexed.dyn_o )
[ 7 of 84] Compiling Control.Lens.Internal.Context ( src/Control/Lens/Internal/Context.hs, dist/build/Control/Lens/Internal/Context.o, dist/build/Control/Lens/Internal/Context.dyn_o )
[ 8 of 84] Compiling Control.Lens.Internal.Bazaar ( src/Control/Lens/Internal/Bazaar.hs, dist/build/Control/Lens/Internal/Bazaar.o, dist/build/Control/Lens/Internal/Bazaar.dyn_o )
[ 9 of 84] Compiling Control.Lens.Internal.Iso ( src/Control/Lens/Internal/Iso.hs, dist/build/Control/Lens/Internal/Iso.o, dist/build/Control/Lens/Internal/Iso.dyn_o )
[10 of 84] Compiling Control.Lens.Internal.Level ( src/Control/Lens/Internal/Level.hs, dist/build/Control/Lens/Internal/Level.o, dist/build/Control/Lens/Internal/Level.dyn_o )
[11 of 84] Compiling Control.Lens.Internal.List ( src/Control/Lens/Internal/List.hs, dist/build/Control/Lens/Internal/List.o, dist/build/Control/Lens/Internal/List.dyn_o )
[12 of 84] Compiling Control.Lens.Internal.Magma ( src/Control/Lens/Internal/Magma.hs, dist/build/Control/Lens/Internal/Magma.o, dist/build/Control/Lens/Internal/Magma.dyn_o )
[13 of 84] Compiling Control.Lens.Internal.Prism ( src/Control/Lens/Internal/Prism.hs, dist/build/Control/Lens/Internal/Prism.o, dist/build/Control/Lens/Internal/Prism.dyn_o )
[14 of 84] Compiling Control.Lens.Internal.Review ( src/Control/Lens/Internal/Review.hs, dist/build/Control/Lens/Internal/Review.o, dist/build/Control/Lens/Internal/Review.dyn_o )
[15 of 84] Compiling Control.Lens.Internal.Setter ( src/Control/Lens/Internal/Setter.hs, dist/build/Control/Lens/Internal/Setter.o, dist/build/Control/Lens/Internal/Setter.dyn_o )
[16 of 84] Compiling Control.Lens.Internal.TH ( src/Control/Lens/Internal/TH.hs, dist/build/Control/Lens/Internal/TH.o, dist/build/Control/Lens/Internal/TH.dyn_o )
[17 of 84] Compiling Control.Lens.Internal.Typeable ( src/Control/Lens/Internal/Typeable.hs, dist/build/Control/Lens/Internal/Typeable.o, dist/build/Control/Lens/Internal/Typeable.dyn_o )
[18 of 84] Compiling Control.Lens.Internal.Zoom ( src/Control/Lens/Internal/Zoom.hs, dist/build/Control/Lens/Internal/Zoom.o, dist/build/Control/Lens/Internal/Zoom.dyn_o )
[19 of 84] Compiling Control.Lens.Internal ( src/Control/Lens/Internal.hs, dist/build/Control/Lens/Internal.o, dist/build/Control/Lens/Internal.dyn_o )
[20 of 84] Compiling Control.Lens.Type ( src/Control/Lens/Type.hs, dist/build/Control/Lens/Type.o, dist/build/Control/Lens/Type.dyn_o )
[21 of 84] Compiling Control.Lens.Setter ( src/Control/Lens/Setter.hs, dist/build/Control/Lens/Setter.o, dist/build/Control/Lens/Setter.dyn_o )
[22 of 84] Compiling Control.Lens.Lens ( src/Control/Lens/Lens.hs, dist/build/Control/Lens/Lens.o, dist/build/Control/Lens/Lens.dyn_o )
[23 of 84] Compiling Control.Lens.Tuple ( src/Control/Lens/Tuple.hs, dist/build/Control/Lens/Tuple.o, dist/build/Control/Lens/Tuple.dyn_o )
[24 of 84] Compiling Control.Lens.Getter ( src/Control/Lens/Getter.hs, dist/build/Control/Lens/Getter.o, dist/build/Control/Lens/Getter.dyn_o )
[25 of 84] Compiling Control.Lens.Review ( src/Control/Lens/Review.hs, dist/build/Control/Lens/Review.o, dist/build/Control/Lens/Review.dyn_o )
[26 of 84] Compiling Control.Lens.Prism ( src/Control/Lens/Prism.hs, dist/build/Control/Lens/Prism.o, dist/build/Control/Lens/Prism.dyn_o )
[27 of 84] Compiling Control.Lens.Fold ( src/Control/Lens/Fold.hs, dist/build/Control/Lens/Fold.o, dist/build/Control/Lens/Fold.dyn_o )
[28 of 84] Compiling Control.Lens.Traversal ( src/Control/Lens/Traversal.hs, dist/build/Control/Lens/Traversal.o, dist/build/Control/Lens/Traversal.dyn_o )
[29 of 84] Compiling Control.Lens.Level ( src/Control/Lens/Level.hs, dist/build/Control/Lens/Level.o, dist/build/Control/Lens/Level.dyn_o )
[30 of 84] Compiling Control.Lens.Reified ( src/Control/Lens/Reified.hs, dist/build/Control/Lens/Reified.o, dist/build/Control/Lens/Reified.dyn_o )
[31 of 84] Compiling Control.Lens.Internal.Exception ( src/Control/Lens/Internal/Exception.hs, dist/build/Control/Lens/Internal/Exception.o, dist/build/Control/Lens/Internal/Exception.dyn_o )
[32 of 84] Compiling Control.Lens.Indexed ( src/Control/Lens/Indexed.hs, dist/build/Control/Lens/Indexed.o, dist/build/Control/Lens/Indexed.dyn_o )
[33 of 84] Compiling Control.Lens.Internal.ByteString ( src/Control/Lens/Internal/ByteString.hs, dist/build/Control/Lens/Internal/ByteString.o, dist/build/Control/Lens/Internal/ByteString.dyn_o )
[34 of 84] Compiling Control.Lens.Equality ( src/Control/Lens/Equality.hs, dist/build/Control/Lens/Equality.o, dist/build/Control/Lens/Equality.dyn_o )
[35 of 84] Compiling Control.Lens.Iso ( src/Control/Lens/Iso.hs, dist/build/Control/Lens/Iso.o, dist/build/Control/Lens/Iso.dyn_o )
[36 of 84] Compiling Control.Lens.Empty ( src/Control/Lens/Empty.hs, dist/build/Control/Lens/Empty.o, dist/build/Control/Lens/Empty.dyn_o )
[37 of 84] Compiling Control.Lens.Cons ( src/Control/Lens/Cons.hs, dist/build/Control/Lens/Cons.o, dist/build/Control/Lens/Cons.dyn_o )
[38 of 84] Compiling Control.Lens.Internal.Deque ( src/Control/Lens/Internal/Deque.hs, dist/build/Control/Lens/Internal/Deque.o, dist/build/Control/Lens/Internal/Deque.dyn_o )
[39 of 84] Compiling Control.Lens.Wrapped ( src/Control/Lens/Wrapped.hs, dist/build/Control/Lens/Wrapped.o, dist/build/Control/Lens/Wrapped.dyn_o )
[40 of 84] Compiling Control.Lens.Zoom ( src/Control/Lens/Zoom.hs, dist/build/Control/Lens/Zoom.o, dist/build/Control/Lens/Zoom.dyn_o )
[41 of 84] Compiling Data.Data.Lens   ( src/Data/Data/Lens.hs, dist/build/Data/Data/Lens.o, dist/build/Data/Data/Lens.dyn_o )
[42 of 84] Compiling Control.Lens.Plated ( src/Control/Lens/Plated.hs, dist/build/Control/Lens/Plated.o, dist/build/Control/Lens/Plated.dyn_o )
[43 of 84] Compiling Data.HashSet.Lens ( src/Data/HashSet/Lens.hs, dist/build/Data/HashSet/Lens.o, dist/build/Data/HashSet/Lens.dyn_o )
[44 of 84] Compiling Data.Map.Lens    ( src/Data/Map/Lens.hs, dist/build/Data/Map/Lens.o, dist/build/Data/Map/Lens.dyn_o )
[45 of 84] Compiling Data.Set.Lens    ( src/Data/Set/Lens.hs, dist/build/Data/Set/Lens.o, dist/build/Data/Set/Lens.dyn_o )
[46 of 84] Compiling Data.Text.Lazy.Lens ( src/Data/Text/Lazy/Lens.hs, dist/build/Data/Text/Lazy/Lens.o, dist/build/Data/Text/Lazy/Lens.dyn_o )
[47 of 84] Compiling Data.Text.Strict.Lens ( src/Data/Text/Strict/Lens.hs, dist/build/Data/Text/Strict/Lens.o, dist/build/Data/Text/Strict/Lens.dyn_o )
[48 of 84] Compiling Data.Text.Lens   ( src/Data/Text/Lens.hs, dist/build/Data/Text/Lens.o, dist/build/Data/Text/Lens.dyn_o )
[49 of 84] Compiling Data.Vector.Generic.Lens ( src/Data/Vector/Generic/Lens.hs, dist/build/Data/Vector/Generic/Lens.o, dist/build/Data/Vector/Generic/Lens.dyn_o )
[50 of 84] Compiling Control.Lens.Each ( src/Control/Lens/Each.hs, dist/build/Control/Lens/Each.o, dist/build/Control/Lens/Each.dyn_o )
[51 of 84] Compiling Control.Lens.At  ( src/Control/Lens/At.hs, dist/build/Control/Lens/At.o, dist/build/Control/Lens/At.dyn_o )
[52 of 84] Compiling Language.Haskell.TH.Lens ( src/Language/Haskell/TH/Lens.hs, dist/build/Language/Haskell/TH/Lens.o, dist/build/Language/Haskell/TH/Lens.dyn_o )

src/Language/Haskell/TH/Lens.hs:2067:5: error:
    • Couldn't match type ‘Exp’ with ‘Maybe Exp’
      Expected type: p [Exp] (f [Exp]) -> p Exp (f Exp)
        Actual type: p [Maybe Exp] (f [Maybe Exp]) -> p Exp (f Exp)
    • In the expression: prism' reviewer remitter
      In an equation for ‘_TupE’:
          _TupE
            = prism' reviewer remitter
            where
                reviewer = TupE
                remitter (TupE x) = Just x
                remitter _ = Nothing
     |
2067 |   = prism' reviewer remitter
     |     ^^^^^^^^^^^^^^^^^^^^^^^^

src/Language/Haskell/TH/Lens.hs:2075:5: error:
    • Couldn't match type ‘Exp’ with ‘Maybe Exp’
      Expected type: p [Exp] (f [Exp]) -> p Exp (f Exp)
        Actual type: p [Maybe Exp] (f [Maybe Exp]) -> p Exp (f Exp)
    • In the expression: prism' reviewer remitter
      In an equation for ‘_UnboxedTupE’:
          _UnboxedTupE
            = prism' reviewer remitter
            where
                reviewer = UnboxedTupE
                remitter (UnboxedTupE x) = Just x
                remitter _ = Nothing
     |
2075 |   = prism' reviewer remitter
     |     ^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build lens-4.18.1
```

### PR DESCRIPTION
**Pull request by RyanGlScott**
This makes four GHC 8.10-related changes:

* The types of `TupE`/`UnboxedTupE` have changed from `[Exp] -> Exp` to `[Maybe Exp] -> Exp` as they now have the ability to support tuple sections. As a result, `Language.Haskell.TH.Lens`' definitions for `_TupE`/`_UnboxedTupE` require some CPP to adapt to the new types.
* Because GHC 8.10 automatically enables `-fobject-code` whenever code that uses `UnboxedTuples` is loaded into GHCi, certain doctests in `lens` will break as a result. (See #874 for more information on why this happens.) Luckily, this is easily avoided by explicitly enabling `-fbyte-code` in one spot.
* `_ForallVisT` and `_BytesPrimL` prisms are now defined when building against `template-haskell-2.16` or later.
* The `HasSubst Type` and `HasTypeVars Type` instances now take `ForallVisT` into account.

Fixes #874. Fixes #894.

### CODE REVIEW

File: src/Language/Haskell/TH/Lens.hs [hunk 1]
```diff
@@ -2057,15 +2114,32 @@ _LamCaseE
...
+#if MIN_VERSION_template_haskell(2,16,0)
+_TupE :: Prism' Exp [Maybe Exp]
+#else
 _TupE :: Prism' Exp [Exp]
+#endif
 _TupE
   = prism' reviewer remitter
   where
       reviewer = TupE
-      remitter (TupE x) = Just x
```
Comment (arybczak) [inline src/Language/Haskell/TH/Lens.hs]: This line shouldn't have been removed, right?

Comment (RyanGlScott) [reply src/Language/Haskell/TH/Lens.hs]: Yikes, that's definitely a mistake! Can you open a PR with a fix? If not, I can do so later at some point.

Comment (RyanGlScott) [reply src/Language/Haskell/TH/Lens.hs]: Resolved in #913, which is present on Hackage as [`lens-4.19.1`](http://hackage.haskell.org/package/lens-4.19.1).
