### ISSUE TITLE
GHC 8.8-related mega-issue

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/lens#845]
There are a handful of changes introduced in GHC 8.8 that will require libraries in the Kmettiverse to adapt:

* `fail` is no longer a method of `Monad`, and `MonadFail` is exported by the `Prelude`.
* The Template Haskell AST has updated alongside GHC's ability to have visible kind applications and more explicit `forall`s in type family equations and `RULES`.

This library tracks all libraries that need to be updated as a result of this. Some libraries will only require minor CPP to accommodate `fail` being removed, while other libraries will require more invasive changes. If you suspect a library nontrivial changes to fix, I will make an effort to open an issue at the library's own issue tracker as well.

(Note: this list is not yet complete. Please add things that are missing, or leave a comment if you can't edit this issue!)

- [X] `bits` ([`bits-0.5.2`](http://hackage.haskell.org/package/bits-0.5.2))
- [X] `bytes` (ekmett/bytes#45) ([`bytes-0.16`](https://hackage.haskell.org/package/bytes-0.16))
- [X] `ersatz` (`exe:ersatz-regexp-grid`) ([`ersatz-0.4.5`](http://hackage.haskell.org/package/ersatz-0.4.5))
- [X] `exceptions` (ekmett/exceptions#68) ([`exceptions-0.10.2`](http://hackage.haskell.org/package/exceptions-0.10.2))
- [X] `free` ([`free-5.1.1`](http://hackage.haskell.org/package/free-5.1.1))
- [X] `lens` ([`lens-4.18`](http://hackage.haskell.org/package/lens-4.18))
- [X] `machines` ([`machines-0.7`](http://hackage.haskell.org/package/machines-0.7))
- [X] `rcu` ([`rcu-0.2.4`](http://hackage.haskell.org/package/rcu-0.2.4))
- [X] `trifecta` ([`trifecta-2.1`](http://hackage.haskell.org/package/trifecta-2.1))
- [X] `zippers` (ekmett/zippers#14) ([`zippers-0.3`](http://hackage.haskell.org/package/zippers-0.3))

**Comment by phadej** [comment]
I also started think. Does it make sense to release `semigroups-0.19` and `void-0.8`, to avoid yet another scan through package-set?

**Comment by RyanGlScott** [comment]
Sure, those are definitely on the agenda as well. (I didn't list `semigroups` or `void` above since they already build with GHC 8.8, so they're in a separate category.)

I could release `semigroup-0.19` today, but I don't have push access to `void`, so the `void-0.9` will require coordination with @ekmett. But let's move this conversation to somewhere else (ekmett/void#17, perhaps), as it doesn't directly relate to this issue.

**Comment by fumieval** [comment]
I manage to get to attempting building lens in this megarepo: https://github.com/haskell-vanguard/haskell-vanguard

As expected, it requires a non-trivial change due to template-haskell:

```
src/Control/Lens/Internal/TH.hs:50:24: error:
    • Couldn't match expected type ‘(TypeQ -> TySynEqnQ) -> DecQ’
                  with actual type ‘Q Dec’
    • The function ‘tySynInstD’ is applied to two arguments,
      but its type ‘TySynEqnQ -> Q Dec’ has only one
      In the expression: tySynInstD fam (tySynEqn ts r)
      In an equation for ‘tySynInstD'’:
          tySynInstD' fam ts r = tySynInstD fam (tySynEqn ts r)
   |
50 | tySynInstD' fam ts r = tySynInstD fam (tySynEqn ts r)
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Control/Lens/Internal/TH.hs:50:35: error:
    • Couldn't match type ‘Name’ with ‘Q TySynEqn’
      Expected type: TySynEqnQ
        Actual type: Name
    • In the first argument of ‘tySynInstD’, namely ‘fam’
      In the expression: tySynInstD fam (tySynEqn ts r)
      In an equation for ‘tySynInstD'’:
          tySynInstD' fam ts r = tySynInstD fam (tySynEqn ts r)
   |
50 | tySynInstD' fam ts r = tySynInstD fam (tySynEqn ts r)
   |                                   ^^^

src/Control/Lens/Internal/TH.hs:50:49: error:
    • Couldn't match expected type ‘Maybe [TyVarBndr]’
                  with actual type ‘[TypeQ]’
    • In the first argument of ‘tySynEqn’, namely ‘ts’
      In the second argument of ‘tySynInstD’, namely ‘(tySynEqn ts r)’
      In the expression: tySynInstD fam (tySynEqn ts r)
   |
50 | tySynInstD' fam ts r = tySynInstD fam (tySynEqn ts r)
```

**Comment by RyanGlScott** [comment]
@fumieval, I have a `ghc-8.8` branch in `lens` which fixes the GHC 8.8-related build errors. That being said, I haven't pushed it through to `master` yet since I'm a bit unclear if we even want to keep `Language.Haskell.TH.Lens` in `lens` in the long run. There has been a separate proposal to just move that module to its own package—see #844.

Of course, regardless of whether we do this or not, we'll still need to have a major version bump on the next `lens` release. The question is what sort of breaking change we wish to make.

**Comment by phadej** [comment]
`wl-pprint-extras`

```
src/Text/PrettyPrint/Free/Internal.hs:805:3: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
805 |   fail _ = empty
    |   ^^^^
```

**Comment by RyanGlScott** [comment]
GHC 8.8-compatible releases of all the libraries on the list (including `lens`) are now on Hackage.
