### ISSUE TITLE
Can't build on GHC 7.10.1

### ISSUE THREAD

**Issue by yongqli** [ekmett/lens#533]
`src/Control/Monad/Primitive/Lens.hs:26:12: Not in scope: ‘internal’`

**Comment by yongqli** [comment]
Looks like this is caused by `primitive-0.6`

**Comment by glguy** [comment]
Released lens has an upper bound which excludes primitive-0.6. HEAD lens builds against primitive-0.6
