### ISSUE TITLE
Benchmark build failure

### ISSUE THREAD

**Issue by bergmark** [ekmett/lens#672]
The benchmarks for this package has been disabled in stackage because of this issue. When a fix is published to hackage could you please send a PR to re-enable the benchmarks to stackage (it's in the expected-benchmark-failures section) or ping me?

Thanks!

```
> /tmp/stackage-build8/lens-4.14$ runghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb Setup configure --enable-benchmarks --package-db=clear --package-db=global --package-db=/var/stackage/work/builds/nightly/pkgdb --libdir=/var/stackage/work/builds/nightly/lib --bindir=/var/stackage/work/builds/nightly/bin --datadir=/var/stackage/work/builds/nightly/share --libexecdir=/var/stackage/work/builds/nightly/libexec --sysconfdir=/var/stackage/work/builds/nightly/etc --docdir=/var/stackage/work/builds/nightly/doc/lens-4.14 --htmldir=/var/stackage/work/builds/nightly/doc/lens-4.14 --haddockdir=/var/stackage/work/builds/nightly/doc/lens-4.14 --flags=

Setup.lhs:55:69: warning: [-Wdeprecations]
    In the use of type constructor or class ‘InstalledPackageId’
    (imported from Distribution.Package):
    Deprecated: "Use UnitId instead"
Configuring lens-4.14...
> /tmp/stackage-build8/lens-4.14$ runghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb Setup build

Setup.lhs:55:69: warning: [-Wdeprecations]
    In the use of type constructor or class ‘InstalledPackageId’
    (imported from Distribution.Package):
    Deprecated: "Use UnitId instead"
Building lens-4.14...
Preprocessing library lens-4.14...
[ 1 of 81] Compiling Paths_lens       ( dist/build/autogen/Paths_lens.hs, dist/build/Paths_lens.o )
[ 2 of 81] Compiling Data.Map.Lens    ( src/Data/Map/Lens.hs, dist/build/Data/Map/Lens.o )
[ 3 of 81] Compiling Control.Lens.Internal.Zoom ( src/Control/Lens/Internal/Zoom.hs, dist/build/Control/Lens/Internal/Zoom.o )
[ 4 of 81] Compiling Control.Lens.Internal.TH ( src/Control/Lens/Internal/TH.hs, dist/build/Control/Lens/Internal/TH.o )
[ 5 of 81] Compiling Control.Lens.Internal.Setter ( src/Control/Lens/Internal/Setter.hs, dist/build/Control/Lens/Internal/Setter.o )
[ 6 of 81] Compiling Control.Lens.Internal.Review ( src/Control/Lens/Internal/Review.hs, dist/build/Control/Lens/Internal/Review.o )
[ 7 of 81] Compiling Control.Lens.Internal.List ( src/Control/Lens/Internal/List.hs, dist/build/Control/Lens/Internal/List.o )
[ 8 of 81] Compiling Control.Lens.Internal.Level ( src/Control/Lens/Internal/Level.hs, dist/build/Control/Lens/Internal/Level.o )
[ 9 of 81] Compiling Control.Lens.Internal.Instances ( src/Control/Lens/Internal/Instances.hs, dist/build/Control/Lens/Internal/Instances.o )
[10 of 81] Compiling Control.Lens.Internal.Getter ( src/Control/Lens/Internal/Getter.hs, dist/build/Control/Lens/Internal/Getter.o )
[11 of 81] Compiling Control.Lens.Internal.Fold ( src/Control/Lens/Internal/Fold.hs, dist/build/Control/Lens/Internal/Fold.o )
[12 of 81] Compiling Control.Lens.Internal.Coerce ( src/Control/Lens/Internal/Coerce.hs, dist/build/Control/Lens/Internal/Coerce.o )
[13 of 81] Compiling Control.Lens.Internal.Indexed ( src/Control/Lens/Internal/Indexed.hs, dist/build/Control/Lens/Internal/Indexed.o )
[14 of 81] Compiling Control.Lens.Internal.Context ( src/Control/Lens/Internal/Context.hs, dist/build/Control/Lens/Internal/Context.o )
[15 of 81] Compiling Control.Lens.Type ( src/Control/Lens/Type.hs, dist/build/Control/Lens/Type.o )
[16 of 81] Compiling Control.Lens.Lens ( src/Control/Lens/Lens.hs, dist/build/Control/Lens/Lens.o )
[17 of 81] Compiling Control.Lens.Tuple ( src/Control/Lens/Tuple.hs, dist/build/Control/Lens/Tuple.o )
[18 of 81] Compiling Control.Lens.Setter ( src/Control/Lens/Setter.hs, dist/build/Control/Lens/Setter.o )
[19 of 81] Compiling Control.Lens.Internal.Iso ( src/Control/Lens/Internal/Iso.hs, dist/build/Control/Lens/Internal/Iso.o )
[20 of 81] Compiling Control.Lens.Internal.Prism ( src/Control/Lens/Internal/Prism.hs, dist/build/Control/Lens/Internal/Prism.o )
[21 of 81] Compiling Control.Lens.Internal.Bazaar ( src/Control/Lens/Internal/Bazaar.hs, dist/build/Control/Lens/Internal/Bazaar.o )
[22 of 81] Compiling Control.Lens.Internal.Magma ( src/Control/Lens/Internal/Magma.hs, dist/build/Control/Lens/Internal/Magma.o )
[23 of 81] Compiling Control.Lens.Internal ( src/Control/Lens/Internal.hs, dist/build/Control/Lens/Internal.o )
[24 of 81] Compiling Control.Lens.Getter ( src/Control/Lens/Getter.hs, dist/build/Control/Lens/Getter.o )
[25 of 81] Compiling Control.Lens.Review ( src/Control/Lens/Review.hs, dist/build/Control/Lens/Review.o )
[26 of 81] Compiling Control.Lens.Prism ( src/Control/Lens/Prism.hs, dist/build/Control/Lens/Prism.o )
[27 of 81] Compiling Control.Lens.Zoom ( src/Control/Lens/Zoom.hs, dist/build/Control/Lens/Zoom.o )
[28 of 81] Compiling Data.HashSet.Lens ( src/Data/HashSet/Lens.hs, dist/build/Data/HashSet/Lens.o )
[29 of 81] Compiling Data.Set.Lens    ( src/Data/Set/Lens.hs, dist/build/Data/Set/Lens.o )
[30 of 81] Compiling Control.Lens.Fold ( src/Control/Lens/Fold.hs, dist/build/Control/Lens/Fold.o )
[31 of 81] Compiling Control.Lens.Internal.Exception ( src/Control/Lens/Internal/Exception.hs, dist/build/Control/Lens/Internal/Exception.o )
[32 of 81] Compiling Control.Lens.Traversal ( src/Control/Lens/Traversal.hs, dist/build/Control/Lens/Traversal.o )
[33 of 81] Compiling Control.Lens.Indexed ( src/Control/Lens/Indexed.hs, dist/build/Control/Lens/Indexed.o )
[34 of 81] Compiling Control.Lens.Internal.ByteString ( src/Control/Lens/Internal/ByteString.hs, dist/build/Control/Lens/Internal/ByteString.o )
[35 of 81] Compiling Control.Lens.Level ( src/Control/Lens/Level.hs, dist/build/Control/Lens/Level.o )
[36 of 81] Compiling Control.Lens.Reified ( src/Control/Lens/Reified.hs, dist/build/Control/Lens/Reified.o )
[37 of 81] Compiling Data.Data.Lens   ( src/Data/Data/Lens.hs, dist/build/Data/Data/Lens.o )
[38 of 81] Compiling Control.Lens.Plated ( src/Control/Lens/Plated.hs, dist/build/Control/Lens/Plated.o )
[39 of 81] Compiling Control.Lens.Equality ( src/Control/Lens/Equality.hs, dist/build/Control/Lens/Equality.o )
[40 of 81] Compiling Control.Lens.Iso ( src/Control/Lens/Iso.hs, dist/build/Control/Lens/Iso.o )
[41 of 81] Compiling Control.Lens.Wrapped ( src/Control/Lens/Wrapped.hs, dist/build/Control/Lens/Wrapped.o )
[42 of 81] Compiling Data.Text.Strict.Lens ( src/Data/Text/Strict/Lens.hs, dist/build/Data/Text/Strict/Lens.o )
[43 of 81] Compiling Data.Text.Lazy.Lens ( src/Data/Text/Lazy/Lens.hs, dist/build/Data/Text/Lazy/Lens.o )
[44 of 81] Compiling Data.Text.Lens   ( src/Data/Text/Lens.hs, dist/build/Data/Text/Lens.o )
[45 of 81] Compiling Data.Vector.Generic.Lens ( src/Data/Vector/Generic/Lens.hs, dist/build/Data/Vector/Generic/Lens.o )
[46 of 81] Compiling Control.Lens.Empty ( src/Control/Lens/Empty.hs, dist/build/Control/Lens/Empty.o )
[47 of 81] Compiling Control.Lens.Each ( src/Control/Lens/Each.hs, dist/build/Control/Lens/Each.o )
[48 of 81] Compiling Control.Lens.Cons ( src/Control/Lens/Cons.hs, dist/build/Control/Lens/Cons.o )
[49 of 81] Compiling Control.Lens.Internal.Deque ( src/Control/Lens/Internal/Deque.hs, dist/build/Control/Lens/Internal/Deque.o )
[50 of 81] Compiling Control.Lens.At  ( src/Control/Lens/At.hs, dist/build/Control/Lens/At.o )
[51 of 81] Compiling Language.Haskell.TH.Lens ( src/Language/Haskell/TH/Lens.hs, dist/build/Language/Haskell/TH/Lens.o )
[52 of 81] Compiling Control.Lens.Internal.FieldTH ( src/Control/Lens/Internal/FieldTH.hs, dist/build/Control/Lens/Internal/FieldTH.o )
[53 of 81] Compiling Control.Lens.Internal.PrismTH ( src/Control/Lens/Internal/PrismTH.hs, dist/build/Control/Lens/Internal/PrismTH.o )
[54 of 81] Compiling Control.Lens.TH  ( src/Control/Lens/TH.hs, dist/build/Control/Lens/TH.o )
[55 of 81] Compiling Control.Lens     ( src/Control/Lens.hs, dist/build/Control/Lens.o )
[56 of 81] Compiling Control.Lens.Combinators ( src/Control/Lens/Combinators.hs, dist/build/Control/Lens/Combinators.o )
[57 of 81] Compiling Control.Lens.Extras ( src/Control/Lens/Extras.hs, dist/build/Control/Lens/Extras.o )
[58 of 81] Compiling Control.Lens.Operators ( src/Control/Lens/Operators.hs, dist/build/Control/Lens/Operators.o )
[59 of 81] Compiling Control.Monad.Error.Lens ( src/Control/Monad/Error/Lens.hs, dist/build/Control/Monad/Error/Lens.o )
[60 of 81] Compiling Control.Parallel.Strategies.Lens ( src/Control/Parallel/Strategies/Lens.hs, dist/build/Control/Parallel/Strategies/Lens.o )
[61 of 81] Compiling Control.Seq.Lens ( src/Control/Seq/Lens.hs, dist/build/Control/Seq/Lens.o )
[62 of 81] Compiling Data.Array.Lens  ( src/Data/Array/Lens.hs, dist/build/Data/Array/Lens.o )
[63 of 81] Compiling Data.Bits.Lens   ( src/Data/Bits/Lens.hs, dist/build/Data/Bits/Lens.o )
[64 of 81] Compiling Data.ByteString.Strict.Lens ( src/Data/ByteString/Strict/Lens.hs, dist/build/Data/ByteString/Strict/Lens.o )
[65 of 81] Compiling Data.ByteString.Lazy.Lens ( src/Data/ByteString/Lazy/Lens.hs, dist/build/Data/ByteString/Lazy/Lens.o )
[66 of 81] Compiling Data.ByteString.Lens ( src/Data/ByteString/Lens.hs, dist/build/Data/ByteString/Lens.o )
[67 of 81] Compiling Data.Complex.Lens ( src/Data/Complex/Lens.hs, dist/build/Data/Complex/Lens.o )
[68 of 81] Compiling Data.IntSet.Lens ( src/Data/IntSet/Lens.hs, dist/build/Data/IntSet/Lens.o )
[69 of 81] Compiling Data.List.Lens   ( src/Data/List/Lens.hs, dist/build/Data/List/Lens.o )
[70 of 81] Compiling Data.Sequence.Lens ( src/Data/Sequence/Lens.hs, dist/build/Data/Sequence/Lens.o )
[71 of 81] Compiling Data.Tree.Lens   ( src/Data/Tree/Lens.hs, dist/build/Data/Tree/Lens.o )
[72 of 81] Compiling Data.Typeable.Lens ( src/Data/Typeable/Lens.hs, dist/build/Data/Typeable/Lens.o )
[73 of 81] Compiling Data.Vector.Lens ( src/Data/Vector/Lens.hs, dist/build/Data/Vector/Lens.o )
[74 of 81] Compiling Generics.Deriving.Lens ( src/Generics/Deriving/Lens.hs, dist/build/Generics/Deriving/Lens.o )
[75 of 81] Compiling GHC.Generics.Lens ( src/GHC/Generics/Lens.hs, dist/build/GHC/Generics/Lens.o )
[76 of 81] Compiling System.FilePath.Lens ( src/System/FilePath/Lens.hs, dist/build/System/FilePath/Lens.o )
[77 of 81] Compiling System.IO.Error.Lens ( src/System/IO/Error/Lens.hs, dist/build/System/IO/Error/Lens.o )
[78 of 81] Compiling Numeric.Lens     ( src/Numeric/Lens.hs, dist/build/Numeric/Lens.o )
[79 of 81] Compiling Control.Exception.Lens ( src/Control/Exception/Lens.hs, dist/build/Control/Exception/Lens.o )
[80 of 81] Compiling Data.Dynamic.Lens ( src/Data/Dynamic/Lens.hs, dist/build/Data/Dynamic/Lens.o )
[81 of 81] Compiling System.Exit.Lens ( src/System/Exit/Lens.hs, dist/build/System/Exit/Lens.o )
Preprocessing benchmark 'plated' for lens-4.14...
[1 of 1] Compiling Main             ( benchmarks/plated.hs, dist/build/plated/plated-tmp/Main.o )

benchmarks/plated.hs:70:70: error:
    • No instance for (Generic Char)
        arising from a use of ‘Generic.tinplate’
    • In the first argument of ‘universeOf’, namely ‘Generic.tinplate’
      In the first argument of ‘map’, namely
        ‘(universeOf Generic.tinplate)’
      In the first argument of ‘nf’, namely
        ‘(map (universeOf Generic.tinplate))’
```

**Comment by RyanGlScott** [comment]
The release of `lens-4.15` fixes the benchmark build on GHC 8.0, at least, so it should suffice for Stackage.
