### ISSUE TITLE
GHC-8.4 related mega-issue

### ISSUE THREAD

**Issue by phadej** [ekmett/lens#781]
Because @RyanGlScott asked me to make one. I'll list my findings here

### Semigroup-Monoid (needs releases)

- [x] https://github.com/ekmett/ad/issues/68 ([Hackage](http://hackage.haskell.org/package/ad-4.3.5))
- [x] https://github.com/ekmett/constraints/pull/65 and https://github.com/ekmett/constraints/pull/70 ([Hackage](http://hackage.haskell.org/package/constraints-0.10))
- [x] https://github.com/ekmett/contravariant/issues/38, PR: https://github.com/ekmett/contravariant/pull/39 ([Hackage](https://hackage.haskell.org/package/contravariant-1.4.1))
- [x] https://github.com/ekmett/ersatz/issues/37 ([Hackage](http://hackage.haskell.org/package/ersatz-0.4.2))
- [x] https://github.com/ekmett/free/pull/155 ([Hackage](http://hackage.haskell.org/package/free-5))
- [ ] https://github.com/ekmett/graphs/pull/10 (Hackage)
- [x] https://github.com/ekmett/heaps/pull/11 ([Hackage](http://hackage.haskell.org/package/heaps-0.3.6))
- [x] https://github.com/ekmett/hybrid-vectors/pull/9 ([Hackage](http://hackage.haskell.org/package/hybrid-vectors-0.2.2))
- [x] https://github.com/ekmett/hyphenation/issues/13 ([Hackage](http://hackage.haskell.org/package/hyphenation-0.7.1))
- [x] https://github.com/ekmett/intern/pull/13 ([Hackage](http://hackage.haskell.org/package/intern-0.9.2))
- [x] [`lca`](https://github.com/ekmett/lca/commit/90d58ba7a67aa13bacc27e59f269508c5837d6f4) ([Hackage](https://hackage.haskell.org/package/lca-0.3.1))
- [x] `lens` itself, https://github.com/ekmett/lens/pull/779 ([Hackage](https://hackage.haskell.org/package/lens-4.16))
- [x] https://github.com/ekmett/lens-action/issues/11 ([Hackage](https://hackage.haskell.org/package/lens-action-0.2.3))
- [x] https://github.com/ekmett/profunctors/pull/58 ([Hackage](http://hackage.haskell.org/package/profunctors-5.2.2))
- [x] https://github.com/ekmett/reflection/pull/37 ([Hackage](http://hackage.haskell.org/package/reflection-2.1.3))
- [x] https://github.com/ekmett/semigroupoids/pull/61 ([Hackage](http://hackage.haskell.org/package/semigroupoids-5.2.2))
- [x] https://github.com/ekmett/zippers/issues/13 ([Hackage](http://hackage.haskell.org/package/zippers-0.2.5))
  
### Intra-dependencies (may need releases)

- [x] `ad` (`free-5`) ([Hackge](https://hackage.haskell.org/package/ad-4.3.5/revisions/))
- [x] `adjunctions` (`free-5`) ([Hackage](http://hackage.haskell.org/package/adjunctions-4.4))
- [x] https://github.com/ekmett/ansi-wl-pprint/pull/16 (`ansi-terminal-0.8`) ([Hackage](https://hackage.haskell.org/package/ansi-wl-pprint-0.6.8.2))
- [x] `kan-extensions` (`free-5`) ([Hackage](http://hackage.haskell.org/package/kan-extensions-5.1))
- [x] `keys` (`free-5`) ([Hackage](http://hackage.haskell.org/package/keys-3.12))
- [x] `recursion-schemes` (`free-5`) ([Hackage](https://hackage.haskell.org/package/recursion-schemes-5.0.2/revisions/))
- ~~https://github.com/ekmett/wl-pprint-terminfo/issues/10 (`wl-pprint-terminfo-3.6`, will need new release)~~

### Lower-bounds (doesn't need releases)

- [x] https://github.com/ekmett/distributive/pull/43

### build-tool-depends (doesn't need releases, but I'll do them anyway)

- [x] https://github.com/ekmett/adjunctions/pull/46 ([Hackage](https://hackage.haskell.org/package/adjunctions-4.4))
- [x] https://github.com/ekmett/bifunctors/pull/66 ([Hackage](http://hackage.haskell.org/package/bifunctors-5.5.1))
- [x] https://github.com/ekmett/constraints/pull/72 ([Hackage](https://hackage.haskell.org/package/constraints-0.10))

### `new-build` shenanigans (doesn't need releases)

- ~~https://github.com/ekmett/gl/issues/17~~

**Comment by phadej** [comment]
@RyanGlScott I get *segmentation fault* when trying to run `doctests` for  `approximate`, `bits`, `compensated` built with

```
% ghc-8.4.1 --version                 
The Glorious Glasgow Haskell Compilation System, version 8.4.0.20171222
% ghc-8.4.1 --print-project-git-commit-id
c6cf13ca63f3a11a8da7c7e3bd69e673a8df5440
```

but e.g. `lens` doctests run fine. Could you check if you can reproduce?

**Comment by RyanGlScott** [comment]
I can take a look during my downtime this week.

Also, since I don't have to do this at the moment: which of the issues in the original comment will require releasing new versions of packages to Hackage? Some of them, like https://github.com/ekmett/distributive/pull/43, don't seem to fall into this category, and it's not clear to me from a quick glance which ones do.

**Comment by RyanGlScott** [comment]
Hm... the `bits` doctests appear to be working for me on 8.4.1, as [this Travis run](https://travis-ci.org/ekmett/bits/jobs/327382819) demonstrates.

**Comment by RyanGlScott** [comment]
The [`approximate`](https://travis-ci.org/ekmett/approximate/jobs/327490321) and [`compensated`](https://travis-ci.org/ekmett/compensated/jobs/327477517) doctests also appear to be in working order.

**Comment by phadej** [comment]
@RyanGlScott 
- I tagged sections for which will need releases (i.e. code changes required), else might be done with revisions only.
- Ok, so problem is probably in my machine, I'll try to run those tests on other box to verify test-pass.

**Comment by RyanGlScott** [comment]
Some updates.

I've updated every. single. Kmett. package. to use `head.hackage` (well, at least those to which I have push access), so now we have some assurance that the Kmettiverse builds on GHC 8.4. The one package I wasn't able to convert was `gl`, as noted in https://github.com/ekmett/gl/issues/17.

Now that everything builds, I've unchecked all of the entries in the `Semigroup`–`Monoid` category, and I'll check them off once they've had proper Hackage releases.

One challenge I'll need to overcome at some point: I don't have push access to `keys` or `reflection`.

Lastly, I was able to reproduce the segfault on the `bits` doctests using Ubuntu 17.04! (All my previous attempts were on Ubuntu 14.04.) This is both fascinating and terrifying. I'll have to investigate further.

**Comment by RyanGlScott** [comment]
I've managed to reduce the segfault down to:

```haskell
module Bug where

{-# ANN module "I'm an annotation" #-}
```
```
$ ./doctest Bug.hs
Segmentation fault (core dumped)
$ ./doctest --version
doctest version 0.13.0
using version 8.4.0.20171222 of the GHC API
using /opt/ghc/8.4.1/bin/ghc-8.4.0.20171222
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
```

**Comment by RyanGlScott** [comment]
And now I can reproduce the issue without `doctest`. See [GHC Trac #14675](https://ghc.haskell.org/trac/ghc/ticket/14675).

**Comment by RyanGlScott** [comment]
New releases for all of the packages in the Semigroup-Monoid column have been uploaded to Hackage—except for `free-5` and `lens-4.16`, since those will require lots of upper version bounds bumping in the ecosystem.

@ekmett @glguy: Can you think of any other changes we should put into `lens-4.16` before a release?

**Comment by RyanGlScott** [comment]
Everything that needs a Hackage release to support GHC 8.4 has now been released. That leaves only two things from the checklist:

* ekmett/wl-pprint-terminfo#10
* ekmett/gl#17

But neither of these are required to support GHC 8.4. I'll opt to close this issue and shift over to the respective remaining issues.

**Comment by phadej** [comment]
@RyanGlScott `lens-4.16` has `template-haskell <2.13`. Is it intentional?

**Comment by RyanGlScott** [comment]
Nope, that certainly wasn't intentional. (I've just made a [commit](https://github.com/ekmett/lens/commit/ef06b4a609c005671b53815792b23f0bf15f7f8d) and a [revision](https://hackage.haskell.org/package/lens-4.16/lens.cabal/edit) to compensate.)

But perhaps we should have a discussion about this. The reason why I didn't notice this in the first place is because our testing infrastructure for GHC 8.4.1 specifies `allow-newer` _carte blanche_ for `template-haskell` (as well as `base`, `Cabal`, and `ghc`), so it's incredibly easy to let upper bounds issues for 8.4.1 slip by unnoticed. What would be ideal is if we could require that these libraries be up-to-date for `lens` itself, but relax them for downstream dependencies (as they haven't all caught up yet, so we can't simply drop `allow-newer` altogether).

(Relatedly, I've often found myself wishing that `new-build` would yell at you more if you are doing illicit things like this—see https://github.com/haskell/cabal/issues/4627, for instance.)

**Comment by phadej** [comment]
@RyanGlScott We don't have a syntax for `allow-newer` to "relax base for everything except these packages". Either we have to explicitly list what needs to be relaxed, or than have somewhat blunt too. (it's still more precise than "--allow-newer" everything).

And relaxing for *this* package is exactly what we want for HEAD, because we don't want to have (in general) to relax upper bound on `base` or `template-haskell` so we don't accidentally release such version (when GHC release is far in the future).

So: bikeshed on the constraint syntax (in a new Cabal issue), maybe we can convince @hvr it has its uses. Maybe `--allow-newer=~lens:template-haskell`. The problem is that `--allow-newer` is disjunctive, so `--allow-newer=~this:base,~that:base` will do wrong thing...

**Comment by phadej** [comment]
```
% cabal --project-file=cabal-8.4.1.project new-build intern -j1
Build profile: -w ghc-8.4.0.20180204 -O1
In order, the following will be built (use -v for more details):
 - intern-0.9.1.4 (lib:intern) (first run)
Preprocessing library for intern-0.9.1.4..
Building library for intern-0.9.1.4..
[2 of 9] Compiling Data.Interned.IntSet ( Data/Interned/IntSet.hs, /home/ogre/Documents/acme-kmett/dist-newstyle/build/x86_64-linux/ghc-8.4.0.20180204/intern-0.9.1.4/build/Data/Interned/IntSet.o )

Data/Interned/IntSet.hs:221:10: error:
    • No instance for (Semigroup IntSet)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid IntSet’
    |
221 | instance Monoid IntSet where
```

ping @RyanGlScott `intern` is broken too

**Comment by phadej** [comment]
```
src/Data/Graph/Algorithm.hs:68:10: error:
    • Could not deduce (Semigroup (GraphSearch g m))
        arising from the superclasses of an instance declaration
      from the context: (Graph g, Monoid m)
        bound by the instance declaration
        at src/Data/Graph/Algorithm.hs:68:10-56
    • In the instance declaration for ‘Monoid (GraphSearch g m)’
   |
68 | instance (Graph g, Monoid m) => Monoid (GraphSearch g m) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build graphs-0.7.
```

**Comment by phadej** [comment]
And other packages currently `acme-kmett` compile fine with GHC-8.4.1, I didn't run test-suites though.

**Comment by RyanGlScott** [comment]
I've uploaded [`intern-0.9.2`](http://hackage.haskell.org/package/intern-0.9.2) and [`graphs-0.7.1`](http://hackage.haskell.org/package/graphs-0.7.1) to Hackage, so _now_ I believe everything is 8.4-ready.
